### ISSUE TITLE
integration gluu server 2.4.3 on liferay 7

### ISSUE THREAD

**Issue by houssine20** [GluuFederation/oxRay#3]
Hello ,

  How to integrate gluu server 2.4.3 on liferay 7 ,because i think this link https://www.gluu.org/docs/integrate/oxray/#deployment document is old version the gluu

Thank you very much. Regards,

**Comment by mzico** [comment]
@houssine20 : Please use support portal for any kind of question; github is bug report only.

**Comment by nynymike** [comment]
oxRay is driven by customer requirements. When an existing customer has a requirement, we will update the code. If your company can fund this enhacement, we have a developer who specializes in LifeRay integrations.
